version: '3'

services:
    web:
        tty: true
        image: python:3.9
        depends_on:
            - db
            - redis
        volumes:
            - .:/opt/url_checker
        container_name: url_checker_web
        ports:
            - "0.0.0.0:8080:8000"
        env_file: .env
        working_dir: /opt/url_checker
        command: /bin/bash -c 'scripts/run_server.sh'
    db:
        image: postgres:12.0-alpine
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        container_name: url_checker_db
        env_file: .env
    redis:
        image: redis:latest
        container_name: url_checker_redis
        env_file: .env
